# SPDX-License-Identifier: Apache-2.0
"""tools/hazard3/shell — a health-test shell's expect.h: what its gen.py
computes and compiles in. exp222 wrote it, exp223 needed it second.

  write_health(out, rv32run, exp, kernel_path, image, counts, wide=False, also=None)

    KERNEL, KERNEL_SHA      the kernel's bytes, checked against its .sha256
    INSTRET_PASS/_FAIL      the Hazard3 RTL's minstret for the kernel on a
                            stream that passes and on one that does not. The
                            kernel's theorem makes the count depend on the
                            verdict alone, so one of each is the count for
                            every stream

  and, before writing anything, the Lean model on the same two images: it
  must halt with 0 after exactly counts[True] on the first and with 1 after
  exactly counts[False] on the second. image(kernel, words) is the image for
  1024 sample words; also(ok, img, region), if given, is any further check of
  the model's region, returning an error message or None.
"""
import random
import sys

from expect import c_bytes, kernel_bin, model, rtl
from streams import N, healthy


def write_health(out, rv32run, exp, kernel_path, image, counts, wide=False, also=None):
    kernel, sha = kernel_bin(kernel_path)
    r = random.Random(int(exp[3:]))
    good = [r.getrandbits(1) for _ in range(N)]
    if not healthy(good)[0]:
        sys.exit("gen.py: the passing stream does not pass")
    measured = {}
    for name, words, ok in (("pass", good, True), ("fail", [1] * N, False)):
        img = image(kernel, words)
        code = 0 if ok else 1
        ran, region = model(rv32run, img, counts[ok] + 10000, wide=wide)
        if ran != f"halt code={code:08x} count={counts[ok]}":
            sys.exit(f"gen.py: on the {name} stream the model said {ran}")
        if also and (why := also(ok, img, region)):
            sys.exit(f"gen.py: on the {name} stream {why}")
        ran = rtl(img, wide=wide)
        if not ran.startswith(f"halt code={code:08x} instret="):
            sys.exit(f"gen.py: on the {name} stream the RTL said {ran}")
        measured[name] = int(ran.split("instret=")[1].split()[0])
    with open(out, "w") as f:
        f.write(f"// Generated by {exp}/gen.py. Do not edit.\n#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define KERNEL_LEN {len(kernel)}\n")
        f.write(f"#define INSTRET_PASS {measured['pass']}u   // the RTL's minstret, HALT 0\n")
        f.write(f"#define INSTRET_FAIL {measured['fail']}u   // and HALT 1\n")
        f.write("static const uint8_t KERNEL[KERNEL_LEN] = {" + c_bytes(kernel) + "};\n")
        f.write("static const uint8_t KERNEL_SHA[32] = {" + c_bytes(bytes.fromhex(sha)) + "};\n")
    return sha, measured
